from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class ProviderRequest(BaseModel):
    """Data contract for sending a generation request to a model provider."""

    prompt: str = Field(..., description="The main user input prompt.")
    system_prompt: Optional[str] = Field(
        None, description="System instructions for the model."
    )
    model: str = Field(..., description="Identifier of the model to use.")
    max_tokens: Optional[int] = Field(
        None, description="Maximum number of tokens to generate."
    )
    temperature: float = Field(0.7, description="Sampling temperature.")


class ProviderResponse(BaseModel):
    """Data contract representing the response generated by a model provider."""

    content: str = Field(..., description="The text generated by the model.")
    model: str = Field(
        ..., description="The identifier of the model that generated the response."
    )
    provider: str = Field(
        ..., description="The name of the provider (e.g., ollama, gemini)."
    )
    token_count: Optional[int] = Field(
        None, description="Estimated token count of the generated response."
    )
    latency_ms: Optional[int] = Field(
        None, description="Time taken to generate response in milliseconds."
    )


class MemoryNode(BaseModel):
    """Data contract representing a semantic piece of knowledge."""

    model_config = ConfigDict(frozen=True)
    id: str = Field(..., description="Unique UUID identifier.")
    session_id: str = Field(
        ..., description="The ID of the session this node belongs to."
    )
    node_type: str = Field(
        ...,
        description="Category of memory: decision, task, bug, file, class, function, api, constraint.",
    )
    content: str = Field(
        ..., description="The text content or fact stored in the node."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Arbitrary metadata attributes."
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    relevance_score: Optional[float] = Field(
        None, description="Relevance score populated on similarity search retrieval."
    )


class MemoryEdge(BaseModel):
    """Data contract representing a typed connection between two memory nodes."""

    model_config = ConfigDict(frozen=True)
    source_id: str = Field(..., description="ID of the source memory node.")
    target_id: str = Field(..., description="ID of the target memory node.")
    relationship: str = Field(
        ...,
        description="Type of relationship: depends_on, implements, references, fixes, modifies, relates_to.",
    )


class ProjectDNA(BaseModel):
    """Data contract representing the detected language, framework, and workspace configuration."""

    language: str = Field(..., description="Primary programming language detected.")
    framework: Optional[str] = Field(
        None, description="Primary web or application framework detected."
    )
    package_manager: Optional[str] = Field(
        None, description="Detected package manager (e.g., pip, npm, cargo)."
    )
    entry_points: List[str] = Field(
        default_factory=list, description="Common entry point files detected."
    )
    database_type: Optional[str] = Field(
        None, description="Inferred database engine/ORM from dependencies."
    )
    architecture_hints: List[str] = Field(
        default_factory=list,
        description="Detected architecture elements (Docker, k8s, etc.).",
    )
    scanned_at: datetime = Field(default_factory=datetime.utcnow)


class SessionState(BaseModel):
    """Data contract representing the live runtime state of the active developer session."""

    session_id: str = Field(
        ..., description="The ID of the session this state belongs to."
    )
    goal: Optional[str] = Field(
        None, description="The primary goal of the active session."
    )
    active_model: str = Field(..., description="The currently selected model.")
    active_provider: str = Field(
        ..., description="The provider of the currently active model."
    )
    current_branch: Optional[str] = Field(
        None, description="The active git branch checked out in the workspace."
    )
    tasks: Dict[str, str] = Field(
        default_factory=dict, description="A dictionary of task_id to task description."
    )
    constraints: List[str] = Field(
        default_factory=list, description="Global constraints or requirements."
    )
    recent_files: List[str] = Field(
        default_factory=list, description="List of recently accessed or modified files."
    )
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Session(BaseModel):
    """Data contract representing a workspace project session."""

    id: str = Field(..., description="Unique UUID identifier.")
    workspace_path: str = Field(
        ..., description="Absolute path to the workspace directory."
    )
    name: str = Field(..., description="Descriptive name of the workspace session.")
    is_active: bool = Field(
        default=False,
        description="Whether this is the currently active workspace session.",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Checkpoint(BaseModel):
    """Data contract representing a historical snapshot of session state."""

    id: str = Field(..., description="Unique UUID identifier.")
    session_id: str = Field(
        ..., description="ID of the session this checkpoint belongs to."
    )
    name: str = Field(..., description="User-provided name of the checkpoint.")
    state_snapshot: Dict[str, Any] = Field(
        ..., description="Serialized JSON of the SessionState."
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class RouterDecision(BaseModel):
    """Data contract representing a routing decision made by the router."""

    provider: str = Field(..., description="The name of the selected provider.")
    model: str = Field(..., description="The identifier of the selected model.")
    intent: str = Field(
        ..., description="The classified query intent (e.g., coding, reasoning)."
    )
    reason: str = Field(
        ..., description="Explanation of why this routing choice was made."
    )


class ContextPayload(BaseModel):
    """Data contract representing the fully compiled prompt payload ready for the provider."""

    system_prompt: str = Field(
        ...,
        description="The assembled system prompt including workspace DNA and rules.",
    )
    user_message: str = Field(
        ..., description="The user prompt containing memory logs, diffs, and query."
    )
    token_estimate: int = Field(
        ..., description="Estimated total token count of the payload."
    )
    memory_nodes_used: List[str] = Field(
        default_factory=list,
        description="IDs of memory nodes used to compile the context.",
    )
    model_hint: Optional[str] = Field(
        None, description="Capability descriptor required for this query."
    )


class PluginResult(BaseModel):
    """Data contract representing the result of executing a plugin action."""

    success: bool = Field(
        ..., description="Whether the plugin action executed successfully."
    )
    output: Optional[str] = Field(
        None, description="The execution output string on success."
    )
    error: Optional[str] = Field(None, description="The error message on failure.")
